name: Kitchen tests for Wazuh Puppet

on: [push, workflow_dispatch]

jobs:

  validate-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y puppet
    - name: Create Puppet module
      run: |
        pdk validate
        pdk new module mymodule
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: mymodule
        path: mymodule

  amazonlinux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Amazon linux - (Manager + Agent)
        uses: './.github/actions/test_manager_and_agent'
        env:
          IMAGE: diodonfrost/amazonlinux-2-puppet
          PLATFORM: rhel
          RELEASE: latest
          RUN_COMMAND: /usr/sbin/init

  centos7:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: CentOS 7 - (Manager + Agent)
        uses: './.github/actions/test_manager_and_agent'
        env:
          IMAGE: centos:7
          PLATFORM: centos
          RELEASE: 7
          RUN_COMMAND: /sbin/init

  ubuntu16:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Ubuntu 16.04 - (Manager + Agent)
        uses: './.github/actions/test_manager_and_agent'
        env:
          IMAGE: jrei/systemd-ubuntu:16.04
          PLATFORM: ubuntu
          RELEASE: 16
          RUN_COMMAND: /sbin/init

  ubuntu18:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Ubuntu 18.04 - (Manager + Agent)
        uses: './.github/actions/test_manager_and_agent'
        env:
          IMAGE: jrei/systemd-ubuntu:18.04
          PLATFORM: ubuntu
          RELEASE: 18
          RUN_COMMAND: /sbin/init
