name: Kitchen tests for Wazuh Puppet

on: [push, workflow_dispatch]

jobs:

  validate-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl apt-transport-https lsb-release wget
    - name: Download and Install Puppet server
      run: |
        wget https://apt.puppet.com/puppet7-release-focal.deb
        sudo dpkg -i puppet7-release-focal.deb
        sudo apt-get update
        sudo apt-get install -y puppetserver
        sudo ln -s /opt/puppetlabs/bin/puppet /bin
        sudo ln -s /opt/puppetlabs/server/bin/puppetserver /bin
    - name: Download and Install pdk
      run: |
        wget https://apt.puppet.com/puppet-tools-release-focal.deb
        sudo dpkg -i puppet-tools-release-focal.deb
        sudo apt-get update
        sudo apt-get install pdk
    - name: Create Puppet module
      run: |
        pdk validate
        pdk build
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: wazuh-module
        path: ./pkg/wazuh-wazuh-${{ env.VERSION }}.tar.gz


#  amazonlinux:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Amazon linux - (Manager + Agent)
#        uses: './.github/actions/test_manager_and_agent'
#        env:
#          IMAGE: diodonfrost/amazonlinux-2-puppet
#          PLATFORM: rhel
#          RELEASE: latest
#          RUN_COMMAND: /usr/sbin/init

#  centos7:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: CentOS 7 - (Manager + Agent)
#        uses: './.github/actions/test_manager_and_agent'
#        env:
#          IMAGE: centos:7
#          PLATFORM: centos
#          RELEASE: 7
#          RUN_COMMAND: /sbin/init

  ubuntu:
    runs-on: ubuntu-latest
    needs: validate-and-build
    steps:
    - uses: actions/checkout@v2
    - name: Create enviroment variables
      run: |
        cat VERSION > $GITHUB_ENV
    - name: create WAZUH_VERSION variable
      run: |
        VERSION=${{ env.WAZUH-PUPPET_VERSION }}
        WAZUH_VERSION=${VERSION:1}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl apt-transport-https lsb-release wget
    - name: Download and Install Puppet server
      run: |
        wget https://apt.puppet.com/puppet7-release-focal.deb
        sudo dpkg -i puppet7-release-focal.deb
        sudo apt-get update
        sudo apt-get install -y puppetserver
        sudo ln -s /opt/puppetlabs/bin/puppet /bin
        sudo ln -s /opt/puppetlabs/server/bin/puppetserver /bin
    - name: Configure puppet server
      run: |
        echo "[main]" | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
        echo "server = "$hostname | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
        echo "dns_alt_names = "$hostname | sudo tee -a /etc/puppetlabs/puppet/puppet.conf > /dev/null
#        echo "server = "$hostname >> /etc/puppetlabs/puppet/puppet.conf
#        echo "dns_alt_names = "$hostname >> /etc/puppetlabs/puppet/puppet.conf
    - name: Start Puppet Server
      run: |
        sudo systemctl start puppetserver
        sudo systemctl enable puppetserver
        sudo systemctl status puppetserver
    - name: Retrieve saved Wazuh module
      uses: actions/download-artifact@v3
      with:
        name: wazuh-module
    - name: Install Wazuh Module
      run: |
        sudo puppet module install ./wazuh-wazuh-${{ env.VERSION }}.tar.gz
    - name: Create manifest for install Wazuh stack
      run: |
        sudo puppetserver ca list --all
        sudo echo "node "${{hostname++" {" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp  > /dev/null
        sudo echo "class {'wazuh::manager':} ->  class {'wazuh::indexer':} -> class {'wazuh::filebeat_oss':} -> class {'wazuh::dashboard':}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null
        sudo echo "}" | sudo tee -a /etc/puppetlabs/code/environments/production/manifests/stack.pp > /dev/null


#  ubuntu18:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#      - name: Ubuntu 18.04 - (Manager + Agent)
#        uses: './.github/actions/test_manager_and_agent'
#        env:
#          IMAGE: jrei/systemd-ubuntu:18.04
#          PLATFORM: ubuntu
#          RELEASE: 18
#          RUN_COMMAND: /sbin/init
